// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Transmission {
    
    
    public partial class TransmissionConfig {
        
        private Gtk.Alignment alignment108;
        
        private Gtk.Table table1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Entry address_entry;
        
        private Gtk.Label remote_port_label;
        
        private Gtk.Entry port_entry;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Entry password_entry;
        
        private Gtk.Entry user_name_entry;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Transmission.TransmissionConfig
            Stetic.BinContainer.Attach(this);
            this.Name = "Transmission.TransmissionConfig";
            // Container child Transmission.TransmissionConfig.Gtk.Container+ContainerChild
            this.alignment108 = new Gtk.Alignment(0.5F, 0F, 1F, 0F);
            this.alignment108.Name = "alignment108";
            // Container child alignment108.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.address_entry = new Gtk.Entry();
            this.address_entry.CanFocus = true;
            this.address_entry.Name = "address_entry";
            this.address_entry.IsEditable = true;
            this.address_entry.InvisibleChar = '●';
            this.hbox1.Add(this.address_entry);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.address_entry]));
            w1.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.remote_port_label = new Gtk.Label();
            this.remote_port_label.Name = "remote_port_label";
            this.remote_port_label.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("Port");
            this.hbox1.Add(this.remote_port_label);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.remote_port_label]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.port_entry = new Gtk.Entry();
            this.port_entry.CanFocus = true;
            this.port_entry.Name = "port_entry";
            this.port_entry.IsEditable = true;
            this.port_entry.WidthChars = 5;
            this.port_entry.MaxLength = 5;
            this.port_entry.InvisibleChar = '●';
            this.hbox1.Add(this.port_entry);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.port_entry]));
            w3.Position = 2;
            w3.Expand = false;
            this.table1.Add(this.hbox1);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.hbox1]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("_Address");
            this.label1.UseUnderline = true;
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("_Password");
            this.label2.UseUnderline = true;
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w6.TopAttach = ((uint)(2));
            w6.BottomAttach = ((uint)(3));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("_Login");
            this.label3.UseUnderline = true;
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.password_entry = new Gtk.Entry();
            this.password_entry.CanFocus = true;
            this.password_entry.Name = "password_entry";
            this.password_entry.IsEditable = true;
            this.password_entry.Visibility = false;
            this.password_entry.InvisibleChar = '●';
            this.table1.Add(this.password_entry);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.password_entry]));
            w8.TopAttach = ((uint)(2));
            w8.BottomAttach = ((uint)(3));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.user_name_entry = new Gtk.Entry();
            this.user_name_entry.CanFocus = true;
            this.user_name_entry.Name = "user_name_entry";
            this.user_name_entry.IsEditable = true;
            this.user_name_entry.InvisibleChar = '●';
            this.table1.Add(this.user_name_entry);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.user_name_entry]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            this.alignment108.Add(this.table1);
            this.Add(this.alignment108);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.user_name_entry.Changed += new System.EventHandler(this.OnUserNameEntryChanged);
            this.password_entry.Changed += new System.EventHandler(this.OnPasswordEntryChanged);
        }
    }
}
