// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.FilesAndFolders {
    
    
    public partial class Configuration {
        
        private Gtk.Alignment alignment1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.VBox vbox1;
        
        private Gtk.Notebook notebook1;
        
        private Gtk.VBox vbox4;
        
        private Gtk.ScrolledWindow index_node_scroll;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label IndexLabel;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button index_remove_btn;
        
        private Gtk.Button index_add_btn;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label maxFileslbl;
        
        private Gtk.Entry numFiles;
        
        private Gtk.CheckButton show_hidden_chk;
        
        private Gtk.Label label1;
        
        private Gtk.VBox vbox5;
        
        private Gtk.ScrolledWindow ignore_node_scroll;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label IgnoreLabel;
        
        private Gtk.HButtonBox hbuttonbox3;
        
        private Gtk.Button ignore_remove_btn;
        
        private Gtk.Button ignore_add_btn;
        
        private Gtk.Label label2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.FilesAndFolders.Configuration
            Stetic.BinContainer.Attach(this);
            this.Name = "Do.FilesAndFolders.Configuration";
            // Container child Do.FilesAndFolders.Configuration.Gtk.Container+ContainerChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.BorderWidth = ((uint)(8));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.HeightRequest = 270;
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 1;
            this.notebook1.ShowBorder = false;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.index_node_scroll = new Gtk.ScrolledWindow();
            this.index_node_scroll.CanFocus = true;
            this.index_node_scroll.Name = "index_node_scroll";
            this.index_node_scroll.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox4.Add(this.index_node_scroll);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox4[this.index_node_scroll]));
            w1.Position = 0;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.IndexLabel = new Gtk.Label();
            this.IndexLabel.Name = "IndexLabel";
            this.hbox1.Add(this.IndexLabel);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.IndexLabel]));
            w2.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.index_remove_btn = new Gtk.Button();
            this.index_remove_btn.CanFocus = true;
            this.index_remove_btn.Name = "index_remove_btn";
            this.index_remove_btn.UseUnderline = true;
            // Container child index_remove_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w3 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w4 = new Gtk.HBox();
            w4.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w5 = new Gtk.Image();
            w5.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Button, 20);
            w4.Add(w5);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w7 = new Gtk.Label();
            w4.Add(w7);
            w3.Add(w4);
            this.index_remove_btn.Add(w3);
            this.hbuttonbox2.Add(this.index_remove_btn);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.index_remove_btn]));
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.index_add_btn = new Gtk.Button();
            this.index_add_btn.CanFocus = true;
            this.index_add_btn.Name = "index_add_btn";
            this.index_add_btn.UseUnderline = true;
            // Container child index_add_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w12 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w13 = new Gtk.HBox();
            w13.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w14 = new Gtk.Image();
            w14.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w13.Add(w14);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w16 = new Gtk.Label();
            w13.Add(w16);
            w12.Add(w13);
            this.index_add_btn.Add(w12);
            this.hbuttonbox2.Add(this.index_add_btn);
            Gtk.ButtonBox.ButtonBoxChild w20 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.index_add_btn]));
            w20.Position = 1;
            w20.Expand = false;
            w20.Fill = false;
            this.hbox1.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox1[this.hbuttonbox2]));
            w21.Position = 1;
            w21.Expand = false;
            this.vbox4.Add(this.hbox1);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.maxFileslbl = new Gtk.Label();
            this.maxFileslbl.Name = "maxFileslbl";
            this.maxFileslbl.LabelProp = Mono.Unix.Catalog.GetString("Maximum number of items to index:");
            this.hbox2.Add(this.maxFileslbl);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox2[this.maxFileslbl]));
            w23.Position = 0;
            w23.Expand = false;
            w23.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.numFiles = new Gtk.Entry();
            this.numFiles.CanFocus = true;
            this.numFiles.Name = "numFiles";
            this.numFiles.IsEditable = true;
            this.numFiles.WidthChars = 5;
            this.numFiles.InvisibleChar = '●';
            this.hbox2.Add(this.numFiles);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox2[this.numFiles]));
            w24.Position = 1;
            w24.Expand = false;
            this.vbox4.Add(this.hbox2);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
            w25.Position = 2;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.show_hidden_chk = new Gtk.CheckButton();
            this.show_hidden_chk.CanFocus = true;
            this.show_hidden_chk.Name = "show_hidden_chk";
            this.show_hidden_chk.Label = Mono.Unix.Catalog.GetString("Show hidden files");
            this.show_hidden_chk.Active = true;
            this.show_hidden_chk.DrawIndicator = true;
            this.show_hidden_chk.UseUnderline = true;
            this.show_hidden_chk.BorderWidth = ((uint)(5));
            this.vbox4.Add(this.show_hidden_chk);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox4[this.show_hidden_chk]));
            w26.Position = 3;
            w26.Expand = false;
            w26.Fill = false;
            this.notebook1.Add(this.vbox4);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Indexed Folders");
            this.notebook1.SetTabLabel(this.vbox4, this.label1);
            this.label1.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.ignore_node_scroll = new Gtk.ScrolledWindow();
            this.ignore_node_scroll.CanFocus = true;
            this.ignore_node_scroll.Name = "ignore_node_scroll";
            this.ignore_node_scroll.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox5.Add(this.ignore_node_scroll);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox5[this.ignore_node_scroll]));
            w28.Position = 0;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.IgnoreLabel = new Gtk.Label();
            this.IgnoreLabel.Name = "IgnoreLabel";
            this.hbox3.Add(this.IgnoreLabel);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.hbox3[this.IgnoreLabel]));
            w29.Position = 0;
            w29.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.hbuttonbox3 = new Gtk.HButtonBox();
            this.hbuttonbox3.Name = "hbuttonbox3";
            // Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
            this.ignore_remove_btn = new Gtk.Button();
            this.ignore_remove_btn.CanFocus = true;
            this.ignore_remove_btn.Name = "ignore_remove_btn";
            this.ignore_remove_btn.UseUnderline = true;
            // Container child ignore_remove_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w30 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w31 = new Gtk.HBox();
            w31.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w32 = new Gtk.Image();
            w32.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Button, 20);
            w31.Add(w32);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w34 = new Gtk.Label();
            w31.Add(w34);
            w30.Add(w31);
            this.ignore_remove_btn.Add(w30);
            this.hbuttonbox3.Add(this.ignore_remove_btn);
            Gtk.ButtonBox.ButtonBoxChild w38 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.ignore_remove_btn]));
            w38.Expand = false;
            w38.Fill = false;
            // Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
            this.ignore_add_btn = new Gtk.Button();
            this.ignore_add_btn.CanFocus = true;
            this.ignore_add_btn.Name = "ignore_add_btn";
            this.ignore_add_btn.UseUnderline = true;
            // Container child ignore_add_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w39 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w40 = new Gtk.HBox();
            w40.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w41 = new Gtk.Image();
            w41.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w40.Add(w41);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w43 = new Gtk.Label();
            w40.Add(w43);
            w39.Add(w40);
            this.ignore_add_btn.Add(w39);
            this.hbuttonbox3.Add(this.ignore_add_btn);
            Gtk.ButtonBox.ButtonBoxChild w47 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.ignore_add_btn]));
            w47.Position = 1;
            w47.Expand = false;
            w47.Fill = false;
            this.hbox3.Add(this.hbuttonbox3);
            Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.hbox3[this.hbuttonbox3]));
            w48.Position = 1;
            w48.Expand = false;
            this.vbox5.Add(this.hbox3);
            Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox3]));
            w49.Position = 1;
            w49.Expand = false;
            w49.Fill = false;
            this.notebook1.Add(this.vbox5);
            Gtk.Notebook.NotebookChild w50 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox5]));
            w50.Position = 1;
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Ignored Folders");
            this.notebook1.SetTabLabel(this.vbox5, this.label2);
            this.label2.ShowAll();
            this.vbox1.Add(this.notebook1);
            Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
            w51.Position = 0;
            this.vbox2.Add(this.vbox1);
            Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.vbox2[this.vbox1]));
            w52.Position = 0;
            this.alignment1.Add(this.vbox2);
            this.Add(this.alignment1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.index_remove_btn.Clicked += new System.EventHandler(this.OnRemoveBtnClicked);
            this.index_add_btn.Clicked += new System.EventHandler(this.OnAddBtnClicked);
            this.numFiles.Changed += new System.EventHandler(this.OnNumFilesEdited);
            this.show_hidden_chk.Clicked += new System.EventHandler(this.OnShowHiddenChkClicked);
            this.ignore_remove_btn.Clicked += new System.EventHandler(this.OnRemoveBtnClicked);
            this.ignore_add_btn.Clicked += new System.EventHandler(this.OnAddBtnClicked);
        }
    }
}
