// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.FilesAndFolders {
    
    
    public partial class Configuration {
        
        private Gtk.Alignment alignment1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow node_scroll;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        private Gtk.Button remove_btn;
        
        private Gtk.Image image3;
        
        private Gtk.Button add_btn;
        
        private Gtk.Image image1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label maxFileslbl;
        
        private Gtk.Entry numFiles;
        
        private Gtk.VBox vbox3;
        
        private Gtk.CheckButton show_hidden_chk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.FilesAndFolders.Configuration
            Stetic.BinContainer.Attach(this);
            this.Name = "Do.FilesAndFolders.Configuration";
            // Container child Do.FilesAndFolders.Configuration.Gtk.Container+ContainerChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.BorderWidth = ((uint)(8));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.node_scroll = new Gtk.ScrolledWindow();
            this.node_scroll.CanFocus = true;
            this.node_scroll.Name = "node_scroll";
            this.node_scroll.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox2.Add(this.node_scroll);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.node_scroll]));
            w1.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.Name = "hbuttonbox1";
            this.hbuttonbox1.Spacing = 4;
            this.hbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.remove_btn = new Gtk.Button();
            this.remove_btn.CanFocus = true;
            this.remove_btn.Name = "remove_btn";
            // Container child remove_btn.Gtk.Container+ContainerChild
            this.image3 = new Gtk.Image();
            this.image3.Name = "image3";
            this.image3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Button, 20);
            this.remove_btn.Add(this.image3);
            this.remove_btn.Label = null;
            this.hbuttonbox1.Add(this.remove_btn);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.remove_btn]));
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.add_btn = new Gtk.Button();
            this.add_btn.CanFocus = true;
            this.add_btn.Name = "add_btn";
            // Container child add_btn.Gtk.Container+ContainerChild
            this.image1 = new Gtk.Image();
            this.image1.Name = "image1";
            this.image1.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Button, 20);
            this.add_btn.Add(this.image1);
            this.add_btn.Label = null;
            this.hbuttonbox1.Add(this.add_btn);
            Gtk.ButtonBox.ButtonBoxChild w5 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.add_btn]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox1.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.maxFileslbl = new Gtk.Label();
            this.maxFileslbl.Name = "maxFileslbl";
            this.maxFileslbl.LabelProp = Mono.Unix.Catalog.GetString("Maximum number of items to index:");
            this.hbox2.Add(this.maxFileslbl);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.maxFileslbl]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.numFiles = new Gtk.Entry();
            this.numFiles.CanFocus = true;
            this.numFiles.Name = "numFiles";
            this.numFiles.IsEditable = true;
            this.numFiles.WidthChars = 5;
            this.numFiles.InvisibleChar = '●';
            this.hbox2.Add(this.numFiles);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox2[this.numFiles]));
            w8.Position = 1;
            w8.Expand = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.show_hidden_chk = new Gtk.CheckButton();
            this.show_hidden_chk.CanFocus = true;
            this.show_hidden_chk.Name = "show_hidden_chk";
            this.show_hidden_chk.Label = Mono.Unix.Catalog.GetString("Show hidden files");
            this.show_hidden_chk.Active = true;
            this.show_hidden_chk.DrawIndicator = true;
            this.show_hidden_chk.UseUnderline = true;
            this.show_hidden_chk.BorderWidth = ((uint)(5));
            this.vbox3.Add(this.show_hidden_chk);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox3[this.show_hidden_chk]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            this.vbox1.Add(this.vbox3);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
            w11.Position = 2;
            w11.Expand = false;
            w11.Fill = false;
            this.vbox2.Add(this.vbox1);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox2[this.vbox1]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            this.alignment1.Add(this.vbox2);
            this.Add(this.alignment1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.remove_btn.Clicked += new System.EventHandler(this.OnRemoveBtnClicked);
            this.add_btn.Clicked += new System.EventHandler(this.OnAddBtnClicked);
            this.numFiles.Changed += new System.EventHandler(this.OnNumFilesEdited);
            this.show_hidden_chk.Clicked += new System.EventHandler(this.OnShowHiddenChkClicked);
        }
    }
}
