// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PingFM {
    
    
    public partial class Configuration {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Table table1;
        
        private Gtk.Entry appkey_entry;
        
        private Gtk.Label appkey_lbl;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label validate_lbl;
        
        private Gtk.Table table2;
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Button validate_btn;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PingFM.Configuration
            Stetic.BinContainer.Attach(this);
            this.Name = "PingFM.Configuration";
            // Container child PingFM.Configuration.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(7));
            // Container child table1.Gtk.Table+TableChild
            this.appkey_entry = new Gtk.Entry();
            this.appkey_entry.CanFocus = true;
            this.appkey_entry.Name = "appkey_entry";
            this.appkey_entry.IsEditable = true;
            this.appkey_entry.InvisibleChar = '●';
            this.table1.Add(this.appkey_entry);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.appkey_entry]));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.appkey_lbl = new Gtk.Label();
            this.appkey_lbl.Name = "appkey_lbl";
            this.appkey_lbl.Ypad = 5;
            this.appkey_lbl.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("Application Key");
            this.table1.Add(this.appkey_lbl);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.appkey_lbl]));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.table1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.validate_lbl = new Gtk.Label();
            this.validate_lbl.Name = "validate_lbl";
            this.validate_lbl.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("<i>Verify and save your account information</i>");
            this.validate_lbl.UseMarkup = true;
            this.vbox2.Add(this.validate_lbl);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.validate_lbl]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.WidthRequest = 119;
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            this.table2.Add(this.fixed1);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.fixed1]));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.validate_btn = new Gtk.Button();
            this.validate_btn.WidthRequest = 40;
            this.validate_btn.CanFocus = true;
            this.validate_btn.Name = "validate_btn";
            this.validate_btn.UseStock = true;
            this.validate_btn.UseUnderline = true;
            this.validate_btn.BorderWidth = ((uint)(7));
            this.validate_btn.Label = "gtk-apply";
            this.table2.Add(this.validate_btn);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this.validate_btn]));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox2[this.table2]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.vbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
            w8.Position = 1;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.validate_btn.Clicked += new System.EventHandler(this.OnApplyBtnClicked);
        }
    }
}
