// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace InlineGoogleSearch {
    
    
    public partial class InlineGoogleSearchConfig {
        
        private Gtk.VBox vbox5;
        
        private Gtk.Frame frame3;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox6;
        
        private Gtk.RadioButton nosafe_rbtn;
        
        private Gtk.RadioButton moderate_rbtn;
        
        private Gtk.RadioButton strict_rbtn;
        
        private Gtk.Label GtkLabel1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget InlineGoogleSearch.InlineGoogleSearchConfig
            Stetic.BinContainer.Attach(this);
            this.Name = "InlineGoogleSearch.InlineGoogleSearchConfig";
            // Container child InlineGoogleSearch.InlineGoogleSearchConfig.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame3.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            // Container child vbox6.Gtk.Box+BoxChild
            this.nosafe_rbtn = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Do not filter my search results."));
            this.nosafe_rbtn.CanFocus = true;
            this.nosafe_rbtn.Name = "nosafe_rbtn";
            this.nosafe_rbtn.DrawIndicator = true;
            this.nosafe_rbtn.UseUnderline = true;
            this.nosafe_rbtn.Group = new GLib.SList(System.IntPtr.Zero);
            this.vbox6.Add(this.nosafe_rbtn);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox6[this.nosafe_rbtn]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.moderate_rbtn = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Use moderate filtering"));
            this.moderate_rbtn.CanFocus = true;
            this.moderate_rbtn.Name = "moderate_rbtn";
            this.moderate_rbtn.DrawIndicator = true;
            this.moderate_rbtn.UseUnderline = true;
            this.moderate_rbtn.Group = this.nosafe_rbtn.Group;
            this.vbox6.Add(this.moderate_rbtn);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox6[this.moderate_rbtn]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.strict_rbtn = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Use strict filtering"));
            this.strict_rbtn.CanFocus = true;
            this.strict_rbtn.Name = "strict_rbtn";
            this.strict_rbtn.DrawIndicator = true;
            this.strict_rbtn.UseUnderline = true;
            this.strict_rbtn.Group = this.nosafe_rbtn.Group;
            this.vbox6.Add(this.strict_rbtn);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox6[this.strict_rbtn]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.GtkAlignment.Add(this.vbox6);
            this.frame3.Add(this.GtkAlignment);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("<b>SafeSearch Preferences</b>");
            this.GtkLabel1.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel1;
            this.vbox5.Add(this.frame3);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox5[this.frame3]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            this.Add(this.vbox5);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.nosafe_rbtn.Toggled += new System.EventHandler(this.OnNosafeRbtnToggled);
            this.moderate_rbtn.Toggled += new System.EventHandler(this.OnModerateRbtnToggled);
            this.strict_rbtn.Toggled += new System.EventHandler(this.OnStrictRbtnToggled);
        }
    }
}
