// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.Riptide {
    
    
    public partial class TorrentDisplay {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label label;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.ProgressBar progressbar;
        
        private Gtk.Button pause_button;
        
        private Gtk.Image pauseplay;
        
        private Gtk.Button cancel_button;
        
        private Gtk.Image image4;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.Riptide.TorrentDisplay
            Stetic.BinContainer.Attach(this);
            this.Name = "Do.Riptide.TorrentDisplay";
            // Container child Do.Riptide.TorrentDisplay.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.vbox1.BorderWidth = ((uint)(5));
            // Container child vbox1.Gtk.Box+BoxChild
            this.label = new Gtk.Label();
            this.label.Name = "label";
            this.label.Xalign = 0F;
            this.label.LabelProp = Mono.Unix.Catalog.GetString("label1");
            this.vbox1.Add(this.label);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.label]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            this.progressbar = new Gtk.ProgressBar();
            this.progressbar.Name = "progressbar";
            this.progressbar.Text = "";
            this.alignment1.Add(this.progressbar);
            this.hbox1.Add(this.alignment1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment1]));
            w3.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.pause_button = new Gtk.Button();
            this.pause_button.CanFocus = true;
            this.pause_button.Name = "pause_button";
            this.pause_button.FocusOnClick = false;
            this.pause_button.Relief = ((Gtk.ReliefStyle)(2));
            // Container child pause_button.Gtk.Container+ContainerChild
            this.pauseplay = new Gtk.Image();
            this.pauseplay.Name = "pauseplay";
            this.pauseplay.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-media-pause", Gtk.IconSize.Menu, 16);
            this.pause_button.Add(this.pauseplay);
            this.pause_button.Label = null;
            this.hbox1.Add(this.pause_button);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.pause_button]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.cancel_button = new Gtk.Button();
            this.cancel_button.CanFocus = true;
            this.cancel_button.Name = "cancel_button";
            this.cancel_button.FocusOnClick = false;
            this.cancel_button.Relief = ((Gtk.ReliefStyle)(2));
            // Container child cancel_button.Gtk.Container+ContainerChild
            this.image4 = new Gtk.Image();
            this.image4.Name = "image4";
            this.image4.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-cancel", Gtk.IconSize.Menu, 16);
            this.cancel_button.Add(this.image4);
            this.cancel_button.Label = null;
            this.hbox1.Add(this.cancel_button);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.cancel_button]));
            w7.Position = 2;
            w7.Expand = false;
            w7.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.pause_button.Clicked += new System.EventHandler(this.OnPauseButtonClicked);
            this.cancel_button.Clicked += new System.EventHandler(this.OnCancelButtonClicked);
        }
    }
}
