// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Do.Plugins.Rss {
    
    
    public partial class Configuration {
        
        private Gtk.Alignment alignment1;
        
        private Gtk.Table table1;
        
        private Gtk.SpinButton CacheDuration;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.FileChooserButton OpmlChooser;
        
        private Gtk.SpinButton Timeout;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Do.Plugins.Rss.Configuration
            Stetic.BinContainer.Attach(this);
            this.Name = "Do.Plugins.Rss.Configuration";
            // Container child Do.Plugins.Rss.Configuration.Gtk.Container+ContainerChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.LeftPadding = ((uint)(6));
            this.alignment1.TopPadding = ((uint)(6));
            this.alignment1.RightPadding = ((uint)(6));
            this.alignment1.BottomPadding = ((uint)(6));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.CacheDuration = new Gtk.SpinButton(0, 100, 1);
            this.CacheDuration.CanFocus = true;
            this.CacheDuration.Name = "CacheDuration";
            this.CacheDuration.Adjustment.PageIncrement = 10;
            this.CacheDuration.ClimbRate = 1;
            this.CacheDuration.Numeric = true;
            this.table1.Add(this.CacheDuration);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.CacheDuration]));
            w1.TopAttach = ((uint)(2));
            w1.BottomAttach = ((uint)(3));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("OPML feed file");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Timeout (in seconds)");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Cache duration (in minutes)");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w4.TopAttach = ((uint)(2));
            w4.BottomAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.OpmlChooser = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
            this.OpmlChooser.Name = "OpmlChooser";
            this.table1.Add(this.OpmlChooser);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.OpmlChooser]));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.Timeout = new Gtk.SpinButton(0, 100, 1);
            this.Timeout.CanFocus = true;
            this.Timeout.Name = "Timeout";
            this.Timeout.Adjustment.PageIncrement = 10;
            this.Timeout.ClimbRate = 1;
            this.Timeout.Numeric = true;
            this.table1.Add(this.Timeout);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.Timeout]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            this.alignment1.Add(this.table1);
            this.Add(this.alignment1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.Timeout.ValueChanged += new System.EventHandler(this.OnTimeoutValueChanged);
            this.OpmlChooser.FileActivated += new System.EventHandler(this.OnOpmlChooserFileActivated);
            this.CacheDuration.ValueChanged += new System.EventHandler(this.OnCacheDurationValueChanged);
        }
    }
}
