// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Tomboy {
    
    
    public partial class TomboyConfiguration {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox2;
        
        private Gtk.CheckButton deriveTitleCheckButton;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.VBox vbox3;
        
        private Gtk.RadioButton contentFirstRadioButton;
        
        private Gtk.RadioButton titleFirstRadioButton;
        
        private Gtk.Label GtkLabel2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Tomboy.TomboyConfiguration
            Stetic.BinContainer.Attach(this);
            this.Name = "Tomboy.TomboyConfiguration";
            // Container child Tomboy.TomboyConfiguration.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            this.frame1.BorderWidth = ((uint)(1));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.deriveTitleCheckButton = new Gtk.CheckButton();
            this.deriveTitleCheckButton.CanFocus = true;
            this.deriveTitleCheckButton.Name = "deriveTitleCheckButton";
            this.deriveTitleCheckButton.Label = Mono.Unix.Catalog.GetString("Use note content as note title when no title is specified.");
            this.deriveTitleCheckButton.DrawIndicator = true;
            this.deriveTitleCheckButton.UseUnderline = true;
            this.vbox2.Add(this.deriveTitleCheckButton);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.deriveTitleCheckButton]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            this.GtkAlignment.Add(this.vbox2);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>Default New Note Title</b>");
            this.GtkLabel3.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel3;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            w4.Padding = ((uint)(5));
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            this.frame2.BorderWidth = ((uint)(1));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.contentFirstRadioButton = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("First pane is content, second pane is title."));
            this.contentFirstRadioButton.CanFocus = true;
            this.contentFirstRadioButton.Name = "contentFirstRadioButton";
            this.contentFirstRadioButton.Active = true;
            this.contentFirstRadioButton.DrawIndicator = true;
            this.contentFirstRadioButton.UseUnderline = true;
            this.contentFirstRadioButton.Group = new GLib.SList(System.IntPtr.Zero);
            this.vbox3.Add(this.contentFirstRadioButton);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.contentFirstRadioButton]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.titleFirstRadioButton = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("First pane is title, second pane is content."));
            this.titleFirstRadioButton.CanFocus = true;
            this.titleFirstRadioButton.Name = "titleFirstRadioButton";
            this.titleFirstRadioButton.DrawIndicator = true;
            this.titleFirstRadioButton.UseUnderline = true;
            this.titleFirstRadioButton.Group = this.contentFirstRadioButton.Group;
            this.vbox3.Add(this.titleFirstRadioButton);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.titleFirstRadioButton]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            this.GtkAlignment1.Add(this.vbox3);
            this.frame2.Add(this.GtkAlignment1);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("<b>New Note Title and Content Entry</b>");
            this.GtkLabel2.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel2;
            this.vbox1.Add(this.frame2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame2]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
