// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RememberTheMilk {
    
    
    public partial class Configuration {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Frame account_frm;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox5;
        
        private Gtk.Label authinfo_lbl;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Fixed fixed5;
        
        private Gtk.Button auth_btn;
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Fixed fixed6;
        
        private Gtk.Label GtkLabel1;
        
        private Gtk.Frame notification_frm;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.VBox vbox3;
        
        private Gtk.CheckButton overdue_chkbtn;
        
        private Gtk.CheckButton confirm_chkbtn;
        
        private Gtk.CheckButton returnnew_chkbtn;
        
        private Gtk.Label GtkLabel5;
        
        private Gtk.Frame filter_frm;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Entry filter_entry;
        
        private Gtk.Label filter_desc_lbl;
        
        private Gtk.HBox info_hbox;
        
        private Gtk.Fixed fixed3;
        
        private Gtk.Fixed fixed4;
        
        private Gtk.Label GtkLabel6;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget RememberTheMilk.Configuration
            Stetic.BinContainer.Attach(this);
            this.Name = "RememberTheMilk.Configuration";
            // Container child RememberTheMilk.Configuration.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.account_frm = new Gtk.Frame();
            this.account_frm.Name = "account_frm";
            this.account_frm.ShadowType = ((Gtk.ShadowType)(0));
            this.account_frm.BorderWidth = ((uint)(2));
            // Container child account_frm.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            this.vbox5.BorderWidth = ((uint)(5));
            // Container child vbox5.Gtk.Box+BoxChild
            this.authinfo_lbl = new Gtk.Label();
            this.authinfo_lbl.Name = "authinfo_lbl";
            this.authinfo_lbl.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("Do needs your authorization in order to manage tasks in your Remember The Milk account. Press the \"Authorize\" button to open a web browser and give Do authorization.");
            this.authinfo_lbl.Wrap = true;
            this.vbox5.Add(this.authinfo_lbl);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox5[this.authinfo_lbl]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.fixed5 = new Gtk.Fixed();
            this.fixed5.Name = "fixed5";
            this.fixed5.HasWindow = false;
            this.hbox1.Add(this.fixed5);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.fixed5]));
            w2.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.auth_btn = new Gtk.Button();
            this.auth_btn.CanFocus = true;
            this.auth_btn.Name = "auth_btn";
            this.auth_btn.UseUnderline = true;
            // Container child auth_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w3 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w4 = new Gtk.HBox();
            w4.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w5 = new Gtk.Image();
            w5.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
            w4.Add(w5);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w7 = new Gtk.Label();
            w7.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("_Authorize");
            w7.UseUnderline = true;
            w4.Add(w7);
            w3.Add(w4);
            this.auth_btn.Add(w3);
            this.hbox1.Add(this.auth_btn);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.auth_btn]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            this.hbox1.Add(this.fixed1);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.fixed1]));
            w12.Position = 2;
            this.vbox5.Add(this.hbox1);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.fixed6 = new Gtk.Fixed();
            this.fixed6.Name = "fixed6";
            this.fixed6.HasWindow = false;
            this.vbox5.Add(this.fixed6);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox5[this.fixed6]));
            w14.Position = 2;
            w14.Expand = false;
            w14.Fill = false;
            this.GtkAlignment.Add(this.vbox5);
            this.account_frm.Add(this.GtkAlignment);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("<b>Account</b>");
            this.GtkLabel1.UseMarkup = true;
            this.account_frm.LabelWidget = this.GtkLabel1;
            this.vbox1.Add(this.account_frm);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox1[this.account_frm]));
            w17.Position = 0;
            w17.Expand = false;
            w17.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.notification_frm = new Gtk.Frame();
            this.notification_frm.Name = "notification_frm";
            this.notification_frm.ShadowType = ((Gtk.ShadowType)(0));
            this.notification_frm.BorderWidth = ((uint)(2));
            // Container child notification_frm.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            this.vbox3.BorderWidth = ((uint)(5));
            // Container child vbox3.Gtk.Box+BoxChild
            this.overdue_chkbtn = new Gtk.CheckButton();
            this.overdue_chkbtn.CanFocus = true;
            this.overdue_chkbtn.Name = "overdue_chkbtn";
            this.overdue_chkbtn.Label = Mono.Addins.AddinManager.CurrentLocalizer.GetString("Show notification for overdue task(s)");
            this.overdue_chkbtn.DrawIndicator = true;
            this.overdue_chkbtn.UseUnderline = true;
            this.vbox3.Add(this.overdue_chkbtn);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox3[this.overdue_chkbtn]));
            w18.Position = 0;
            w18.Expand = false;
            w18.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.confirm_chkbtn = new Gtk.CheckButton();
            this.confirm_chkbtn.CanFocus = true;
            this.confirm_chkbtn.Name = "confirm_chkbtn";
            this.confirm_chkbtn.Label = Mono.Addins.AddinManager.CurrentLocalizer.GetString("Show notification when actions are completed");
            this.confirm_chkbtn.DrawIndicator = true;
            this.confirm_chkbtn.UseUnderline = true;
            this.vbox3.Add(this.confirm_chkbtn);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox3[this.confirm_chkbtn]));
            w19.Position = 1;
            w19.Expand = false;
            w19.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.returnnew_chkbtn = new Gtk.CheckButton();
            this.returnnew_chkbtn.CanFocus = true;
            this.returnnew_chkbtn.Name = "returnnew_chkbtn";
            this.returnnew_chkbtn.Label = Mono.Addins.AddinManager.CurrentLocalizer.GetString("Return the newly created task");
            this.returnnew_chkbtn.DrawIndicator = true;
            this.returnnew_chkbtn.UseUnderline = true;
            this.vbox3.Add(this.returnnew_chkbtn);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox3[this.returnnew_chkbtn]));
            w20.Position = 2;
            w20.Expand = false;
            w20.Fill = false;
            this.GtkAlignment2.Add(this.vbox3);
            this.notification_frm.Add(this.GtkAlignment2);
            this.GtkLabel5 = new Gtk.Label();
            this.GtkLabel5.Name = "GtkLabel5";
            this.GtkLabel5.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("<b>Interactivity</b>");
            this.GtkLabel5.UseMarkup = true;
            this.notification_frm.LabelWidget = this.GtkLabel5;
            this.vbox1.Add(this.notification_frm);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox1[this.notification_frm]));
            w23.Position = 1;
            w23.Expand = false;
            w23.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.filter_frm = new Gtk.Frame();
            this.filter_frm.Name = "filter_frm";
            this.filter_frm.ShadowType = ((Gtk.ShadowType)(0));
            this.filter_frm.BorderWidth = ((uint)(2));
            // Container child filter_frm.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            this.vbox4.BorderWidth = ((uint)(5));
            // Container child vbox4.Gtk.Box+BoxChild
            this.filter_entry = new Gtk.Entry();
            this.filter_entry.CanFocus = true;
            this.filter_entry.Name = "filter_entry";
            this.filter_entry.IsEditable = true;
            this.filter_entry.InvisibleChar = '●';
            this.vbox4.Add(this.filter_entry);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox4[this.filter_entry]));
            w24.Position = 0;
            w24.Expand = false;
            w24.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.filter_desc_lbl = new Gtk.Label();
            this.filter_desc_lbl.Name = "filter_desc_lbl";
            this.filter_desc_lbl.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("You can enter some advanced search operators here to limit the tasks Do indexes. E.g. \"priority:1 AND status:incomplete\" will force Do to only index all incomplete tasks with high priority.");
            this.filter_desc_lbl.Wrap = true;
            this.vbox4.Add(this.filter_desc_lbl);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox4[this.filter_desc_lbl]));
            w25.Position = 1;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.info_hbox = new Gtk.HBox();
            this.info_hbox.Name = "info_hbox";
            this.info_hbox.Spacing = 6;
            // Container child info_hbox.Gtk.Box+BoxChild
            this.fixed3 = new Gtk.Fixed();
            this.fixed3.Name = "fixed3";
            this.fixed3.HasWindow = false;
            this.info_hbox.Add(this.fixed3);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.info_hbox[this.fixed3]));
            w26.Position = 0;
            // Container child info_hbox.Gtk.Box+BoxChild
            this.fixed4 = new Gtk.Fixed();
            this.fixed4.Name = "fixed4";
            this.fixed4.HasWindow = false;
            this.info_hbox.Add(this.fixed4);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.info_hbox[this.fixed4]));
            w27.Position = 2;
            this.vbox4.Add(this.info_hbox);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox4[this.info_hbox]));
            w28.Position = 2;
            w28.Expand = false;
            w28.Fill = false;
            this.GtkAlignment3.Add(this.vbox4);
            this.filter_frm.Add(this.GtkAlignment3);
            this.GtkLabel6 = new Gtk.Label();
            this.GtkLabel6.Name = "GtkLabel6";
            this.GtkLabel6.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("<b>Filter</b>");
            this.GtkLabel6.UseMarkup = true;
            this.filter_frm.LabelWidget = this.GtkLabel6;
            this.vbox1.Add(this.filter_frm);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox1[this.filter_frm]));
            w31.Position = 2;
            w31.Expand = false;
            w31.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.notification_frm.Hide();
            this.filter_frm.Hide();
            this.Show();
            this.auth_btn.Clicked += new System.EventHandler(this.OnAuthBtnClicked);
            this.overdue_chkbtn.Clicked += new System.EventHandler(this.OnOverdueChkbtnClicked);
            this.confirm_chkbtn.Clicked += new System.EventHandler(this.OnConfirmChkbtnClicked);
            this.returnnew_chkbtn.Clicked += new System.EventHandler(this.OnReturnNewChkBtnClicked);
            this.filter_entry.Changed += new System.EventHandler(this.OnFilterEntryChanged);
        }
    }
}
