// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Pastebin {
    
    
    public partial class PastebinConfig {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox2;
        
        private Gtk.ComboBox cmbProvider;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label lblCodes;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView treeCodes;
        
        private Gtk.Label GtkLabel3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Pastebin.PastebinConfig
            Stetic.BinContainer.Attach(this);
            this.Name = "Pastebin.PastebinConfig";
            // Container child Pastebin.PastebinConfig.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.cmbProvider = Gtk.ComboBox.NewText();
            this.cmbProvider.Name = "cmbProvider";
            this.vbox2.Add(this.cmbProvider);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.cmbProvider]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.lblCodes = new Gtk.Label();
            this.lblCodes.Name = "lblCodes";
            this.lblCodes.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("Supported Codes\t\t\t");
            this.hbox1.Add(this.lblCodes);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.lblCodes]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.treeCodes = new Gtk.TreeView();
            this.treeCodes.CanFocus = true;
            this.treeCodes.Name = "treeCodes";
            this.treeCodes.EnableSearch = false;
            this.treeCodes.HeadersVisible = false;
            this.GtkScrolledWindow.Add(this.treeCodes);
            this.vbox2.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
            w5.Position = 2;
            this.GtkAlignment.Add(this.vbox2);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Addins.AddinManager.CurrentLocalizer.GetString("<b>Pastebin Provider</b>");
            this.GtkLabel3.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel3;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w8.Position = 0;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.cmbProvider.Changed += new System.EventHandler(this.cmbProviderChanged);
        }
    }
}
