// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Translate {
    
    
    public partial class ConfigUI {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label lblProvider;
        
        private Gtk.ComboBox cmbProvider;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label lblDefaultSource;
        
        private Gtk.ComboBox cmbDefaultSource;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label lblDefaultIface;
        
        private Gtk.ComboBox cmbDefaultIface;
        
        private Gtk.Label lblEnabled;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView treeEnableLang;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Translate.ConfigUI
            Stetic.BinContainer.Attach(this);
            this.Name = "Translate.ConfigUI";
            // Container child Translate.ConfigUI.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.LeftPadding = ((uint)(4));
            this.alignment1.TopPadding = ((uint)(4));
            this.alignment1.RightPadding = ((uint)(4));
            this.alignment1.BottomPadding = ((uint)(4));
            this.alignment1.BorderWidth = ((uint)(4));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.lblProvider = new Gtk.Label();
            this.lblProvider.Name = "lblProvider";
            this.lblProvider.LabelProp = Mono.Unix.Catalog.GetString("Translation Provider");
            this.hbox1.Add(this.lblProvider);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.lblProvider]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.cmbProvider = Gtk.ComboBox.NewText();
            this.cmbProvider.Name = "cmbProvider";
            this.hbox1.Add(this.cmbProvider);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.cmbProvider]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            w2.Padding = ((uint)(10));
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.lblDefaultSource = new Gtk.Label();
            this.lblDefaultSource.Name = "lblDefaultSource";
            this.lblDefaultSource.LabelProp = Mono.Unix.Catalog.GetString("Default Source Language");
            this.hbox2.Add(this.lblDefaultSource);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.lblDefaultSource]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.cmbDefaultSource = new Gtk.ComboBox();
            this.cmbDefaultSource.Name = "cmbDefaultSource";
            this.hbox2.Add(this.cmbDefaultSource);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.cmbDefaultSource]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            w5.Padding = ((uint)(10));
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.lblDefaultIface = new Gtk.Label();
            this.lblDefaultIface.Name = "lblDefaultIface";
            this.lblDefaultIface.LabelProp = Mono.Unix.Catalog.GetString("Default Web Interface Language");
            this.hbox3.Add(this.lblDefaultIface);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox3[this.lblDefaultIface]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.cmbDefaultIface = new Gtk.ComboBox();
            this.cmbDefaultIface.Name = "cmbDefaultIface";
            this.hbox3.Add(this.cmbDefaultIface);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.cmbDefaultIface]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            w8.Padding = ((uint)(10));
            this.vbox2.Add(this.hbox3);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
            w9.Position = 2;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.lblEnabled = new Gtk.Label();
            this.lblEnabled.Name = "lblEnabled";
            this.lblEnabled.LabelProp = Mono.Unix.Catalog.GetString("Supported Languages");
            this.vbox2.Add(this.lblEnabled);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.lblEnabled]));
            w10.Position = 3;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.treeEnableLang = new Gtk.TreeView();
            this.treeEnableLang.CanFocus = true;
            this.treeEnableLang.Name = "treeEnableLang";
            this.GtkScrolledWindow.Add(this.treeEnableLang);
            this.vbox2.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
            w12.Position = 4;
            this.alignment1.Add(this.vbox2);
            this.vbox1.Add(this.alignment1);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
            w14.Position = 0;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.cmbProvider.Changed += new System.EventHandler(this.ProviderSelectionChanged);
            this.cmbDefaultSource.Changed += new System.EventHandler(this.SourceSelectionChanged);
            this.cmbDefaultIface.Changed += new System.EventHandler(this.IfaceSelectionChanged);
        }
    }
}
