// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DoTwitter {
    
    
    public partial class Configuration {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Table table1;
        
        private Gtk.Entry passwd_entry;
        
        private Gtk.Label passwd_lbl;
        
        private Gtk.Entry username_entry;
        
        private Gtk.Label username_lbl;
        
        private Gtk.VBox vbox3;
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label valid_lbl;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Fixed fixed5;
        
        private Gtk.Button apply_btn;
        
        private Gtk.Fixed fixed6;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Fixed fixed4;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Table table2;
        
        private Gtk.Label label1;
        
        private Gtk.Table table3;
        
        private Gtk.Fixed fixed2;
        
        private Gtk.Fixed fixed3;
        
        private Gtk.Button new_acct;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DoTwitter.Configuration
            Stetic.BinContainer.Attach(this);
            this.Name = "DoTwitter.Configuration";
            // Container child DoTwitter.Configuration.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.passwd_entry = new Gtk.Entry();
            this.passwd_entry.CanFocus = true;
            this.passwd_entry.Name = "passwd_entry";
            this.passwd_entry.IsEditable = true;
            this.passwd_entry.Visibility = false;
            this.passwd_entry.InvisibleChar = '●';
            this.table1.Add(this.passwd_entry);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.passwd_entry]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XPadding = ((uint)(10));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.passwd_lbl = new Gtk.Label();
            this.passwd_lbl.Name = "passwd_lbl";
            this.passwd_lbl.Xalign = 1F;
            this.passwd_lbl.LabelProp = Mono.Unix.Catalog.GetString("Password");
            this.table1.Add(this.passwd_lbl);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.passwd_lbl]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.username_entry = new Gtk.Entry();
            this.username_entry.CanFocus = true;
            this.username_entry.Name = "username_entry";
            this.username_entry.IsEditable = true;
            this.username_entry.InvisibleChar = '●';
            this.table1.Add(this.username_entry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.username_entry]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XPadding = ((uint)(10));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.username_lbl = new Gtk.Label();
            this.username_lbl.Name = "username_lbl";
            this.username_lbl.Xalign = 1F;
            this.username_lbl.LabelProp = Mono.Unix.Catalog.GetString("Username");
            this.table1.Add(this.username_lbl);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.username_lbl]));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox2[this.table1]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.valid_lbl = new Gtk.Label();
            this.valid_lbl.Name = "valid_lbl";
            this.valid_lbl.LabelProp = Mono.Unix.Catalog.GetString("<i>Please test your Twitter account info</i>");
            this.valid_lbl.UseMarkup = true;
            this.vbox1.Add(this.valid_lbl);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.valid_lbl]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.fixed5 = new Gtk.Fixed();
            this.fixed5.Name = "fixed5";
            this.fixed5.HasWindow = false;
            this.hbox1.Add(this.fixed5);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.fixed5]));
            w7.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.apply_btn = new Gtk.Button();
            this.apply_btn.WidthRequest = 105;
            this.apply_btn.CanFocus = true;
            this.apply_btn.Name = "apply_btn";
            this.apply_btn.UseUnderline = true;
            // Container child apply_btn.Gtk.Container+ContainerChild
            Gtk.Alignment w8 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w9 = new Gtk.HBox();
            w9.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w10 = new Gtk.Image();
            w10.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
            w9.Add(w10);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w12 = new Gtk.Label();
            w12.LabelProp = Mono.Unix.Catalog.GetString("_Validate");
            w12.UseUnderline = true;
            w9.Add(w12);
            w8.Add(w9);
            this.apply_btn.Add(w8);
            this.hbox1.Add(this.apply_btn);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox1[this.apply_btn]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.fixed6 = new Gtk.Fixed();
            this.fixed6.Name = "fixed6";
            this.fixed6.HasWindow = false;
            this.hbox1.Add(this.fixed6);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox1[this.fixed6]));
            w17.Position = 2;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            this.vbox1.Add(this.vbox4);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
            w19.Position = 2;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.fixed4 = new Gtk.Fixed();
            this.fixed4.Name = "fixed4";
            this.fixed4.HasWindow = false;
            this.hbox2.Add(this.fixed4);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox2[this.fixed4]));
            w20.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.WidthRequest = 250;
            this.hseparator1.Name = "hseparator1";
            this.hbox2.Add(this.hseparator1);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox2[this.hseparator1]));
            w21.Position = 1;
            // Container child hbox2.Gtk.Box+BoxChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            this.hbox2.Add(this.fixed1);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox2[this.fixed1]));
            w22.Position = 2;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w23.Position = 3;
            w23.Expand = false;
            w23.Fill = false;
            this.vbox3.Add(this.vbox1);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox3[this.vbox1]));
            w24.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(4)), ((uint)(1)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(1));
            this.table2.ColumnSpacing = ((uint)(1));
            // Container child table2.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<i>Don't have a Twitter account?</i>");
            this.label1.UseMarkup = true;
            this.table2.Add(this.label1);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table2[this.label1]));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.table3 = new Gtk.Table(((uint)(1)), ((uint)(3)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.fixed2 = new Gtk.Fixed();
            this.fixed2.Name = "fixed2";
            this.fixed2.HasWindow = false;
            this.table3.Add(this.fixed2);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table3[this.fixed2]));
            w26.LeftAttach = ((uint)(2));
            w26.RightAttach = ((uint)(3));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.fixed3 = new Gtk.Fixed();
            this.fixed3.Name = "fixed3";
            this.fixed3.HasWindow = false;
            this.table3.Add(this.fixed3);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table3[this.fixed3]));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.new_acct = new Gtk.Button();
            this.new_acct.CanFocus = true;
            this.new_acct.Name = "new_acct";
            this.new_acct.UseUnderline = true;
            this.new_acct.Label = Mono.Unix.Catalog.GetString("Sign up for Twitter");
            this.table3.Add(this.new_acct);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table3[this.new_acct]));
            w28.LeftAttach = ((uint)(1));
            w28.RightAttach = ((uint)(2));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            this.table2.Add(this.table3);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table2[this.table3]));
            w29.TopAttach = ((uint)(1));
            w29.BottomAttach = ((uint)(4));
            w29.YPadding = ((uint)(5));
            w29.XOptions = ((Gtk.AttachOptions)(4));
            w29.YOptions = ((Gtk.AttachOptions)(0));
            this.vbox3.Add(this.table2);
            Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.vbox3[this.table2]));
            w30.Position = 1;
            w30.Expand = false;
            w30.Fill = false;
            this.vbox2.Add(this.vbox3);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
            w31.Position = 1;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.apply_btn.Clicked += new System.EventHandler(this.OnApplyBtnClicked);
            this.new_acct.Clicked += new System.EventHandler(this.OnNewAcctClicked);
        }
    }
}
