// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Flickr {
    
    
    public partial class UploadDialog {
        
        private Gtk.Alignment alignment1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Image FlickrImage;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label TextLabel;
        
        private Gtk.ProgressBar uploadProgress;
        
        private Gtk.Button HideButton;
        
        private Gtk.Button OKButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Flickr.UploadDialog
            this.Name = "Flickr.UploadDialog";
            this.Title = Mono.Unix.Catalog.GetString("Flickr Upload");
            this.Icon = Gdk.Pixbuf.LoadFromResource("flickr.png");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.SkipTaskbarHint = true;
            this.HasSeparator = false;
            // Internal child Flickr.UploadDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.LeftPadding = ((uint)(10));
            this.alignment1.TopPadding = ((uint)(10));
            this.alignment1.RightPadding = ((uint)(10));
            this.alignment1.BottomPadding = ((uint)(10));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.FlickrImage = new Gtk.Image();
            this.FlickrImage.Name = "FlickrImage";
            this.hbox1.Add(this.FlickrImage);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.FlickrImage]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.TextLabel = new Gtk.Label();
            this.TextLabel.Name = "TextLabel";
            this.TextLabel.Justify = ((Gtk.Justification)(2));
            this.TextLabel.Ellipsize = ((Pango.EllipsizeMode)(3));
            this.TextLabel.WidthChars = 40;
            this.vbox2.Add(this.TextLabel);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.TextLabel]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.uploadProgress = new Gtk.ProgressBar();
            this.uploadProgress.Name = "uploadProgress";
            this.vbox2.Add(this.uploadProgress);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.uploadProgress]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w5.Position = 1;
            this.alignment1.Add(this.hbox1);
            w1.Add(this.alignment1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(w1[this.alignment1]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Internal child Flickr.UploadDialog.ActionArea
            Gtk.HButtonBox w8 = this.ActionArea;
            w8.Name = "dialog1_ActionArea";
            w8.Spacing = 6;
            w8.BorderWidth = ((uint)(5));
            w8.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.HideButton = new Gtk.Button();
            this.HideButton.CanDefault = true;
            this.HideButton.CanFocus = true;
            this.HideButton.Name = "HideButton";
            this.HideButton.UseUnderline = true;
            // Container child HideButton.Gtk.Container+ContainerChild
            Gtk.Alignment w9 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w10 = new Gtk.HBox();
            w10.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w11 = new Gtk.Image();
            w11.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-leave-fullscreen", Gtk.IconSize.LargeToolbar, 24);
            w10.Add(w11);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w13 = new Gtk.Label();
            w13.LabelProp = Mono.Unix.Catalog.GetString("_Hide");
            w13.UseUnderline = true;
            w10.Add(w13);
            w9.Add(w10);
            this.HideButton.Add(w9);
            this.AddActionWidget(this.HideButton, 0);
            Gtk.ButtonBox.ButtonBoxChild w17 = ((Gtk.ButtonBox.ButtonBoxChild)(w8[this.HideButton]));
            w17.Expand = false;
            w17.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.OKButton = new Gtk.Button();
            this.OKButton.CanFocus = true;
            this.OKButton.Name = "OKButton";
            this.OKButton.UseUnderline = true;
            // Container child OKButton.Gtk.Container+ContainerChild
            Gtk.Alignment w18 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            Gtk.HBox w19 = new Gtk.HBox();
            w19.Spacing = 2;
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Image w20 = new Gtk.Image();
            w20.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-ok", Gtk.IconSize.LargeToolbar, 24);
            w19.Add(w20);
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Label w22 = new Gtk.Label();
            w22.LabelProp = Mono.Unix.Catalog.GetString("_OK");
            w22.UseUnderline = true;
            w19.Add(w22);
            w18.Add(w19);
            this.OKButton.Add(w18);
            this.AddActionWidget(this.OKButton, 0);
            Gtk.ButtonBox.ButtonBoxChild w26 = ((Gtk.ButtonBox.ButtonBoxChild)(w8[this.OKButton]));
            w26.Position = 1;
            w26.Expand = false;
            w26.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 408;
            this.DefaultHeight = 147;
            this.Show();
        }
    }
}
