// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JIRA {
    
    
    public partial class ConfigWidget {
        
        private Gtk.Table table2;
        
        private Gtk.Entry _entryBaseUrl;
        
        private Gtk.Entry _entryPassword;
        
        private Gtk.Entry _entryProjects;
        
        private Gtk.Entry _entryUsername;
        
        private Gtk.Label _labelBaseUrl;
        
        private Gtk.Label _labelPassword;
        
        private Gtk.Label _labelProjects;
        
        private Gtk.Label _labelUsername;
        
        private Gtk.Button _saveButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget JIRA.ConfigWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "JIRA.ConfigWidget";
            // Container child JIRA.ConfigWidget.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this._entryBaseUrl = new Gtk.Entry();
            Gtk.Tooltips w1 = new Gtk.Tooltips();
            w1.SetTip(this._entryBaseUrl, "The base url location to your JIRA install. ie. http://issues.apache.org/jira", "The base url location to your JIRA install. ie. http://issues.apache.org/jira");
            this._entryBaseUrl.CanFocus = true;
            this._entryBaseUrl.Name = "_entryBaseUrl";
            this._entryBaseUrl.Text = "http://issues.apache.org/issues";
            this._entryBaseUrl.IsEditable = true;
            this._entryBaseUrl.InvisibleChar = '●';
            this.table2.Add(this._entryBaseUrl);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this._entryBaseUrl]));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this._entryPassword = new Gtk.Entry();
            this._entryPassword.CanFocus = true;
            this._entryPassword.Name = "_entryPassword";
            this._entryPassword.IsEditable = true;
            this._entryPassword.Visibility = false;
            this._entryPassword.InvisibleChar = '●';
            this.table2.Add(this._entryPassword);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this._entryPassword]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this._entryProjects = new Gtk.Entry();
            w1.SetTip(this._entryProjects, "Comma separated list of projects", "Comma separated list of projects");
            this._entryProjects.CanFocus = true;
            this._entryProjects.Name = "_entryProjects";
            this._entryProjects.Text = "VFS,NET";
            this._entryProjects.IsEditable = true;
            this._entryProjects.InvisibleChar = '●';
            this.table2.Add(this._entryProjects);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this._entryProjects]));
            w4.TopAttach = ((uint)(3));
            w4.BottomAttach = ((uint)(4));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this._entryUsername = new Gtk.Entry();
            this._entryUsername.CanFocus = true;
            this._entryUsername.Name = "_entryUsername";
            this._entryUsername.Text = "username1";
            this._entryUsername.IsEditable = true;
            this._entryUsername.InvisibleChar = '●';
            this.table2.Add(this._entryUsername);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this._entryUsername]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this._labelBaseUrl = new Gtk.Label();
            this._labelBaseUrl.Name = "_labelBaseUrl";
            this._labelBaseUrl.LabelProp = "Base Url";
            this.table2.Add(this._labelBaseUrl);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this._labelBaseUrl]));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this._labelPassword = new Gtk.Label();
            this._labelPassword.Name = "_labelPassword";
            this._labelPassword.LabelProp = "Password";
            this.table2.Add(this._labelPassword);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table2[this._labelPassword]));
            w7.TopAttach = ((uint)(2));
            w7.BottomAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this._labelProjects = new Gtk.Label();
            this._labelProjects.Name = "_labelProjects";
            this._labelProjects.LabelProp = "Projects";
            this.table2.Add(this._labelProjects);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table2[this._labelProjects]));
            w8.TopAttach = ((uint)(3));
            w8.BottomAttach = ((uint)(4));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this._labelUsername = new Gtk.Label();
            this._labelUsername.Name = "_labelUsername";
            this._labelUsername.LabelProp = "Username";
            this.table2.Add(this._labelUsername);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this._labelUsername]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this._saveButton = new Gtk.Button();
            this._saveButton.CanFocus = true;
            this._saveButton.Name = "_saveButton";
            this._saveButton.UseUnderline = true;
            this._saveButton.Xalign = 0F;
            this._saveButton.Label = "Save";
            this.table2.Add(this._saveButton);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table2[this._saveButton]));
            w10.TopAttach = ((uint)(4));
            w10.BottomAttach = ((uint)(5));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(0));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this._saveButton.Released += new System.EventHandler(this.OnSaveButtonReleased);
        }
    }
}
